### ISSUE TITLE
Outgoing call state

### ISSUE THREAD

**Issue by AbdurRehman-coder** [andreamainella98/phone_state#10]
How could we know about the outgoing call state, I am working on a project in flutter where I need to know the status of the outgoing calls. So would anyone can help me with this?

**Comment by Mohammad-Hosein88** [comment]
We really need it, has it been implemented yet?

**Comment by Mohammad-Hosein88** [comment]
I just checked the package and found out that it already supports it. When your app is running and you go on and make a call with your sim, the OFF_HOOK state in android is returned which in dart side is CALL_STARTED. Hope it helps you
@AbdurRehman-coder
