### ISSUE TITLE
Comment Récupérer le numéro de téléphone lors d'un appel entrant 

### ISSUE THREAD

**Issue by adoupatrick9** [andreamainella98/phone_state#13]
Salut j'espère que mon message vous trouve en bonne santé.
J'aimerai savoir s'il était possible de récupérer le numéro de téléphone(contact ou non) lors d'un appel entrant sur android et IOS.
merci.

**Comment by andreamainella98** [comment]
#14

**Comment by andreamainella98** [comment]
Duplicate #14
