### ISSUE TITLE
[FEATURE] Recover phone number

### ISSUE THREAD

**Issue by andreamainella98** [andreamainella98/phone_state#14]
## FEATURE
- Retrieve the phone number from an incoming call

**Comment by 19119294973** [comment]
I want to get not only the call status, but also the call information number

**Comment by andreamainella98** [comment]
Completed!

The phone number is only obtainable on Android for the moment :(

PR:
https://github.com/andreamainella98/phone_state/pull/17

**Comment by SOG-gen** [comment]
Does this work on android 10 upward.

Because according to android docs,  `This constant was deprecated in API level 29.
Companion apps for wearable devices should use the [InCallService](https://developer.android.com/reference/android/telecom/InCallService) API to retrieve the phone number for calls instead. Apps performing call screening should use the [CallScreeningService](https://developer.android.com/reference/android/telecom/CallScreeningService) API instead.`

https://developer.android.com/reference/android/telephony/TelephonyManager#EXTRA_INCOMING_NUMBER

Will it work on API level 29 and higher

**Comment by berkekbgz** [comment]
> Does this work on android 10 upward.
> 
> Because according to android docs, `This constant was deprecated in API level 29. Companion apps for wearable devices should use the [InCallService](https://developer.android.com/reference/android/telecom/InCallService) API to retrieve the phone number for calls instead. Apps performing call screening should use the [CallScreeningService](https://developer.android.com/reference/android/telecom/CallScreeningService) API instead.`
> 
> https://developer.android.com/reference/android/telephony/TelephonyManager#EXTRA_INCOMING_NUMBER
> 
> Will it work on API level 29 and higher

It is working on my Android 11 (level 30). 

But using `CallScreeningService` (if im not missing anything) not working if the application is not setted as dialer application under the devices below level 29. [Source](https://stackoverflow.com/a/58803250/11084704).

**Comment by SOG-gen** [comment]
> > Does this work on android 10 upward.
> > Because according to android docs, `This constant was deprecated in API level 29. Companion apps for wearable devices should use the [InCallService](https://developer.android.com/reference/android/telecom/InCallService) API to retrieve the phone number for calls instead. Apps performing call screening should use the [CallScreeningService](https://developer.android.com/reference/android/telecom/CallScreeningService) API instead.`
> > https://developer.android.com/reference/android/telephony/TelephonyManager#EXTRA_INCOMING_NUMBER
> > Will it work on API level 29 and higher
> 
> It is working on my Android 11 (level 30).
> 
> But using `CallScreeningService` (if im not missing anything) not working if the application is not setted as dialer application under the devices below level 29. [Source](https://stackoverflow.com/a/58803250/11084704).

Yes, that true, am just wondering what will happen in other higher android versions as we proceed,since this
https://developer.android.com/reference/android/telephony/TelephonyManager#EXTRA_INCOMING_NUMBER has already been depreciated

**Comment by SOG-web** [comment]
Please just wanted to ask

Do I see the incoming phone number on iOS also ?
