### ISSUE TITLE
iOS cannot make it work in background

### ISSUE THREAD

**Issue by steveroseik** [andreamainella98/phone_state#28]
I'm having an issue, I'm using it to track the call duration but it doesn't work as once the app is out of focus and the phone call starts it doesn't capture unless the phone call ends, and then the call_start is at the same time of the call_end

**Comment by JadyMcIntyre** [comment]
Any updates?

**Comment by bhargav6744** [comment]
I am facing same issue...

**Comment by andreamainella98** [comment]
@steveroseik @JadyMcIntyre @bhargav6744 Merry christmas to everyone, check pub.dev 🎄🎉

**Comment by steveroseik** [comment]
> @steveroseik @JadyMcIntyre @bhargav6744 Merry christmas to everyone, check pub.dev 🎄🎉

This is great news! Thank youu so much and merry christmas🎄🎉
