### ISSUE TITLE
intial state of the phone also we need like if the person is already on a call and opening the app 

### ISSUE THREAD

**Issue by MINEGHOST007** [andreamainella98/phone_state#29]
intial state of the phone also we need like if the person is already on a call and opening the app

**Comment by MINEGHOST007** [comment]
something like PhoneState.instance should give present state may be using audio session get devices or request focus we can find a solution

**Comment by kirilllapshev** [comment]
This would be amazing!

**Comment by andreamainella98** [comment]
Integrated on version 2.0.0, Thanks 🫶🏼
