### ISSUE TITLE
Won't work in background (When the app is terminated) mode

### ISSUE THREAD

**Issue by SmilingFarood** [andreamainella98/phone_state#3]
Hi, I tried to listen to phoneStateStream in background mode but I keep getting this error
`Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: PHONE_STATE_STREAM. Response ID: 20`

**Comment by SmilingFarood** [comment]
I tried to find the cause of the issue but I am yet to get to the depth. I saw a possible cause and solution [here](https://stackoverflow.com/a/69935199/15842901) but it still looks vague to me

<img width="909" alt="image" src="https://user-images.githubusercontent.com/58653583/170493726-40666cc9-07db-4e5b-834d-d2f23c75d197.png">

**Comment by andreamainella98** [comment]
@SmilingFarood Hi, I didn't understand correctly, are you trying to call the plugin services from an app terminated, completely terminated, or simply from an app in the background? In case it was the second option, have you created an android service that is activated when the app is sent to the background?

[Service example](https://www.tutorialspoint.com/how-to-run-an-android-service-always-in-the-background-using-kotlin)

**Comment by SmilingFarood** [comment]
I am trying to call the plugin services from a terminated app. It works well in the background.

**Comment by andreamainella98** [comment]
Hi @SmilingFarood, 
sorry if I answer you only now but it has been a busy week, however have you succeeded in your intent?🤔
