### ISSUE TITLE
CALL_OUTGOING Status required

### ISSUE THREAD

**Issue by KunjKanani** [andreamainella98/phone_state#4]

**Comment by andreamainella98** [comment]
@KunjKanani please add more information, thanks

**Comment by AbdurRehman-coder** [comment]
I also need this feature, to know about the outgoing call status, which means when a call is started and when attend the call, and at end of the call, So I can record the voice between attending and end of the call, Please Andrea guide me through this

**Comment by Mohammad-Hosein88** [comment]
@KunjKanani Check my response here #10

**Comment by andreamainella98** [comment]
Completed on #10
