### ISSUE TITLE
[FEATURE] Get if the out going call was answer

### ISSUE THREAD

**Issue by hydev777** [andreamainella98/phone_state#8]
Hello, it would be great if we could know if the call was answer, we currently only have these statuses: `NOTHING, CALL_ENDED, CALL_INCOMING and CALL_STARTED`. When we start to make a call we immediately get the status `CALL_STARTED` and then we get  CALL_ENDED either if we hang up the call or the person we are calling to ends the call, so there is no a way to know when was hanged up by the caller or the person we are calling to. Please consider to add this feature since will add more functionality to this package.

**Comment by andreamainella98** [comment]
Duplicate #15
